// 44: Error handling in Rust - time to panic!

fn main() {
    
}
